export interface PrivacySection {
  id: string;
  title: string;
  paragraphs?: string[];
  bullets?: string[];
  closingParagraphs?: string[];
}

export const PRIVACY_EFFECTIVE_DATE = "July 15, 2026";
export const PRIVACY_VERSION = "MVP Release Version 1.0";

export const PRIVACY_SECTIONS: PrivacySection[] = [
  {
    id: "introduction",
    title: "1. Introduction",
    paragraphs: [
      "This Privacy Policy explains how Speeky (“we,” “our,” or “us”) collects, uses, stores, and protects information when you use the Speeky AI communication coaching application (the “Software”).",
      "By using Speeky, you agree to the collection and use of information in accordance with this Policy. If you do not agree with this Policy, please discontinue use of the Software.",
    ],
  },
  {
    id: "information-we-collect",
    title: "2. Information We Collect",
    paragraphs: ["Depending on how you use Speeky, we may collect:"],
    bullets: [
      "Account information — name, email address, and password (stored as a secure hash, never in plain text).",
      "Practice session data — audio recordings, speech transcriptions, and text you submit during conversation practice.",
      "Performance data — fluency, confidence, and pronunciation scores generated by our AI models.",
      "Technical data — device type, browser, and general usage patterns needed to keep the Software running reliably.",
    ],
  },
  {
    id: "how-we-use",
    title: "3. How We Use Your Information",
    paragraphs: ["We use collected information to:"],
    bullets: [
      "Provide, maintain, and improve the AI coaching experience.",
      "Generate personalized feedback, scores, and progress tracking.",
      "Authenticate your account and keep your session secure.",
      "Respond to support requests and account-related communications.",
      "Detect and prevent misuse, fraud, or abuse of the Software.",
    ],
    closingParagraphs: [
      "We do not sell your personal information to third parties.",
    ],
  },
  {
    id: "local-processing",
    title: "4. Local and Offline Processing",
    paragraphs: [
      "Where supported, Speeky is designed to process speech locally on your device.",
      "In these cases, audio recordings and transcriptions may remain on your device and are not automatically transmitted to external servers unless a feature explicitly requires it (for example, syncing progress to your account).",
    ],
  },
  {
    id: "data-sharing",
    title: "5. Data Sharing and Third Parties",
    paragraphs: [
      "We may share limited data with third-party infrastructure providers strictly to operate the Software, such as hosting and email delivery for account and password-reset messages.",
      "These providers are contractually limited to using your data only to perform services on our behalf.",
    ],
  },
  {
    id: "data-retention",
    title: "6. Data Retention",
    paragraphs: [
      "We retain account and practice-session data for as long as your account remains active.",
      "You may request deletion of your account and associated data at any time; some data may be retained briefly afterward where required for security or legal purposes.",
    ],
  },
  {
    id: "security",
    title: "7. Data Security",
    paragraphs: [
      "We use industry-standard measures to protect your data, including encrypted password storage, HTTPS in production, and access-controlled infrastructure.",
      "No method of transmission or storage is 100% secure, and we cannot guarantee absolute security.",
    ],
  },
  {
    id: "your-rights",
    title: "8. Your Rights",
    paragraphs: ["Depending on your jurisdiction, you may have the right to:"],
    bullets: [
      "Access the personal data we hold about you.",
      "Request correction of inaccurate data.",
      "Request deletion of your account and data.",
      "Withdraw consent for optional data processing at any time.",
    ],
  },
  {
    id: "children",
    title: "9. Children's Privacy",
    paragraphs: [
      "Speeky is not intended for use by individuals under the minimum legal age in their jurisdiction without appropriate parental or guardian consent.",
    ],
  },
  {
    id: "changes",
    title: "10. Changes to This Policy",
    paragraphs: [
      "We may update this Privacy Policy periodically. Continued use of Speeky after changes are published indicates acceptance of the updated Policy.",
    ],
  },
  {
    id: "contact",
    title: "11. Contact Information",
    paragraphs: [
      "For questions or requests regarding this Privacy Policy or your personal data, please contact the Speeky development team through the official project communication channels.",
    ],
  },
];
